stages:
  - build
  - test
  - release

build:
  stage: build
  image: registry.git.foxido.dev/foxido/nyacc-rs/ci_image
  script:
    - cargo build
  cache:
    paths:
      - target

runtest:
  stage: test
  image: registry.git.foxido.dev/foxido/nyacc-rs/ci_image
  cache:
    paths:
      - target
  script:
    - cargo test -- -Z unstable-options --format json --report-time | cargo2junit > results.xml
  artifacts:
    reports:
      junit: results.xml

codestyle:
  stage: test
  image: registry.git.foxido.dev/foxido/nyacc-rs/ci_image
  cache:
    paths:
      - target
  script:
    - cargo fmt --check

build_release:
  stage: release
  image: registry.git.foxido.dev/foxido/nyacc-rs/ci_image
  only:
  - master
  cache:
    paths:
      - target
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/nyacc