stages:
  - build
  - test
  - release

build:
  stage: build
  image: rust
  script:
    - cargo build
  cache:
    paths:
      - target

runtest:
  stage: test
  image: rust
  cache:
    paths:
      - target
  script:
    - cargo test

codestyle:
  stage: test
  image: rust
  cache:
    paths:
      - target
  script:
    - rustup component add rustfmt
    - cargo fmt --check

build_release:
  stage: release
  image: rust
  only:
  - master
  cache:
    paths:
      - target
  script:
    - cargo build release
  artifacts:
    paths:
      - target/release/nyacc